# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d04b1f32b88e7132e2b64474bd277e26e982eb1f7f7ce189081d2d42ce9c48f2d0bbdee3351fed5fa81a428349015842e950d68ad1427c9e7e57641bcac6d3e8

test:
  secret_key_base: 4970a3607732b45d09cebef9aab7a59ab9140e5a71a21e2ab4429eb2feeb82e88c81ae24c40368f1413cf4c6da940c3725079d9feb92a54def15e9a6ae3d569d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
